import { AvatarsExports, MediaExports } from "./media-exports";
import { IChat, IUser, Message } from "./Interfaces";

export const userData: IUser = {
  id: 20,
  avatar: AvatarsExports.Avatar_1,
  email: "ilya@yandex.ru",
  login: "ilya-andreevi4",
  first_name: "Ilya",
  second_name: "Orekhov",
  display_name: "Ilya-Andreevi4",
  phone: "+7 (909) 967 30 30",
  password: "string",
  status: "online",
};

export const chatsData: IChat[] = [
  {
    id: 0,
    avatar: AvatarsExports.Avatar_2,
    title: "Ryan Gosling",
    last_message: {
      user: {
        first_name: "Ryan",
        second_name: "Gosling",
        avatar: AvatarsExports.Avatar_2,
        email: "my@email.com",
        login: "Ryan_Gosling",
        phone: "8(911)-222-33-22",
      },
      time: "2020-01-02T14:03:22.000Z",
      content: "Image...",
    },
    unread_count: 2,
    isActive: false,
    status: "online",
    isGroup: false,
  },
  {
    id: 1,
    avatar: AvatarsExports.Avatar_3,
    title: "Marie Laforet",
    last_message: {
      user: {
        first_name: "Marie",
        second_name: "Laforet",
        avatar: AvatarsExports.Avatar_3,
        email: "my@email.com",
        login: "Marie_Laforet",
        phone: "8(911)-222-33-22",
      },
      time: "2020-01-02T13:33:22.000Z",
      content: "Ok",
    },
    isActive: false,
    status: "offline",
    isGroup: false,
  },
  {
    id: 2,
    avatar: AvatarsExports.Avatar_4,
    title: "Johnny Cash",
    last_message: {
      user: {
        first_name: "Johnny",
        second_name: "Cash",
        avatar: AvatarsExports.Avatar_4,
        email: "my@email.com",
        login: "Johnny_Cash",
        phone: "8(911)-222-33-22",
      },
      time: "2020-01-02T15:41:22.000Z",
      content: "Amazing!",
    },
    isActive: true,
    status: "online",
    isGroup: false,
  },
  {
    id: 3,
    title: "Project's chat",
    avatar: AvatarsExports.Avatar_6,
    last_message: {
      user: {
        first_name: "Johnny",
        second_name: "Cash",
        avatar: AvatarsExports.Avatar_4,
        email: "my@email.com",
        login: "Johnny_Cash",
        phone: "8(911)-222-33-22",
      },
      time: "2020-01-02T14:03:22.000Z",
      content: "Got it.",
    },
    unread_count: 12,
    isActive: false,
    isGroup: true,
    users: [
      {
        id: 4,
        avatar: "/src/static/media/avatar-1.jpg",
        first_name: "Ilya",
        second_name: "Orekhov",
        status: "online",
      },
      {
        id: 5,
        avatar: "/src/static/media/avatar-2.jpg",
        first_name: "Ryan",
        second_name: "Gosling",
        status: "online",
      },
      {
        id: 6,
        avatar: "/src/static/media/avatar-3.jpg",
        first_name: "Marie",
        second_name: "Laforet",
        status: "offline",
      },
      {
        id: 7,
        avatar: "/src/static/media/avatar-4.jpg",
        first_name: "Johnny",
        second_name: "Cash",
        status: "online",
      },
    ],
  },
  {
    id: 8,
    title: "Marie's Birthday",
    avatar: AvatarsExports.Avatar_5,
    last_message: {
      user: {
        first_name: "Johnny",
        second_name: "Cash",
        avatar: AvatarsExports.Avatar_4,
        email: "my@email.com",
        login: "Johnny_Cash",
        phone: "8(911)-222-33-22",
      },
      time: "2020-01-02T14:44:22.000Z",
      content: "Video...",
    },
    isActive: false,
    isGroup: true,
    users: [
      {
        id: 9,
        avatar: "/src/static/media/avatar-1.jpg",
        first_name: "Ilya",
        second_name: "Orekhov",
        status: "online",
      },
      {
        id: 10,
        avatar: "/src/static/media/avatar-2.jpg",
        first_name: "Ryan",
        second_name: "Gosling",
        status: "online",
      },
      {
        id: 11,
        avatar: "/src/static/media/avatar-4.jpg",
        first_name: "Johnny",
        second_name: "Cash",
        status: "online",
      },
    ],
  },
];

export const messagesData: Message[] = [
  {
    time: "2020-01-02T14:02:22.000Z",
    chat_id: 0,
    type: "message",
    user_id: 0,
    content: "Hi! Look at this!",
  },
  {
    time: "2020-01-02T14:03:22.000Z",
    chat_id: 0,
    type: "message",
    user_id: 0,
    content: "",
    file: {
      id: 1212,
      user_id: 0,
      path: MediaExports.ChatPhoto,
      filename: "",
      content_type: "image/jpg",
      content_size: 0,
      upload_date: "2020-01-02T14:03:22.000Z",
    },
  },
  {
    time: "2020-01-02T08:36:22.000Z",
    chat_id: 1,
    type: "message",
    user_id: 628175,
    content: "Hi Marie, I'm sick today, can you cover for me at work?",
    // file: {
    //   id: 121,
    //   user_id: 1,
    //   path: MediaExports.ChatPhoto,
    //   filename: "",
    //   content_type: "image/jpg",
    //   content_size: 0,
    //   upload_date: "2020-01-02T14:03:22.000Z",
    // },
  },
  {
    time: "2020-01-02T13:33:22.000Z",
    chat_id: 1,
    type: "message",
    user_id: 1,
    content: "Ok",
  },
  {
    time: "2020-01-02T08:36:22.000Z",
    chat_id: 2,
    type: "message",
    user_id: 2,
    content: "Hi, I'm sick today, can you cover for me at work?",
    file: {
      id: 121,
      user_id: 2,
      path: MediaExports.ChatPhoto_2,
      filename: "",
      content_type: "image/jpg",
      content_size: 0,
      upload_date: "2020-01-02T08:36:22.000Z",
    },
  },
  {
    time: "2020-01-02T08:51:22.000Z",
    chat_id: 2,
    type: "message",
    user_id: 628175,
    content: "Johnny hi! Yeah, sure, no problem. Get well!",
  },
  {
    time: "2020-01-02T09:13:22.000Z",
    chat_id: 2,
    type: "message",
    user_id: 2,
    content: "Thank you! Good luck!",
  },
  {
    time: "2020-01-02T14:56:22.000Z",
    chat_id: 2,
    type: "message",
    user_id: 628175,
    content: "",
    file: {
      id: 121,
      user_id: 628175,
      path: MediaExports.ChatPhoto,
      filename: "",
      content_type: "image/jpg",
      content_size: 0,
      upload_date: "2020-01-02T14:56:22.000Z",
    },
  },
  {
    time: "2020-01-02T15:41:22.000Z",
    chat_id: 2,
    type: "message",
    user_id: 2,
    content: "Amazing!",
    file: {
      id: 121,
      user_id: 628175,
      path: MediaExports.ChatPhoto,
      filename: "",
      content_type: "image/jpg",
      content_size: 0,
      upload_date: "2020-01-02T14:56:22.000Z",
    },
  },
  {
    time: "2020-01-02T08:36:22.000Z",
    chat_id: 3,
    type: "message",
    user_id: 2,
    content: "Hi evebody! I'm sick today, can someone cover for me at work?",
    // file: {
    //   id: 121,
    //   user_id: 628175,
    //   path: MediaExports.ChatPhoto,
    //   filename: "",
    //   content_type: "image/jpg",
    //   content_size: 0,
    //   upload_date: "2020-01-02T14:56:22.000Z",
    // },
  },
  {
    time: "2020-01-02T08:36:22.000Z",
    chat_id: 3,
    type: "message",
    user_id: 2,
    content: "Hi evebody! I'm sick today, can someone cover for me at work?",
  },
  // {
  //   authorID: 3,
  //   messages: [
  //     {
  //       from: "Johnny Cash",
  //       text: `Hi evebody! I'm sick today, can someone cover for me at work?`,
  //       time: "2020-01-02T08:36:22.000Z",
  //       my: false,
  //     },
  //     {
  //       from: "You",
  //       text: "Johnny hi! Yeah, sure, no problem. Get well!",
  //       time: "2020-01-02T08:51:22.000Z",
  //       my: true,
  //     },
  //     {
  //       from: "Johnny Cash",
  //       text: "Got it.",
  //       time: "2020-01-02T14:03:22.000Z",
  //       my: false,
  //     },
  //   ],
  // },
  // {
  //   author: "Marie's Birthday",
  //   authorID: 8,
  //   messages: [
  //     {
  //       from: "Johnny Cash",
  //       text: `Hi evebody! What shall we give Marie for her birthday?`,
  //       time: "2020-01-02T08:36:22.000Z",
  //       my: false,
  //     },
  //     {
  //       from: "You",
  //       text: "How about this?",
  //       time: "2020-01-02T14:40:22.000Z",
  //       my: true,
  //     },
  //     {
  //       from: "You",
  //       image: AvatarsExports.Avatar_5,
  //       time: "2020-01-02T14:44:22.000Z",
  //       my: true,
  //     },
  //   ],
  // },
];
